remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-readme-index
  - jekyll-relative-links

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false

relative_links:
  enabled: true
  collections: true

# Make relative markdown links on Pages resolve to .html automatically
markdown_ext: "md,mkd,mkdn,markdown"
permalink: pretty

# Ensure index.md is used as the site homepage
readme_index:
  with_frontmatter: true

sass:
  style: compressed
